### PR TITLE
#169817806 Update TravisCI to run tests

### PR DESCRIPTION
**Pull request by jo-rdan**
### What does this PR do?
- It updates the TravisCI to run tests
### Description of Task to be completed?
- add travis.yml file
- add Travis badge on the readme file
### How should this be manually tested?
- When a branch is pushed to GitHub, a build is started and if it passes, there is a green tick and if not, there is a red cross next to the PR
### Any background context you want to provide?
- this is to update Travis to run tests and initially we do not have tests so it has to fail
### What are the relevant pivotal tracker stories?
[#169817806](https://www.pivotaltracker.com/story/show/169817806)
### Screenshots (if appropriate)
image
image

### CODE REVIEW

**Comment by Ruqoyah** [comment]
@jo-rdan Why does Travis pass in your PR without test written?

**Comment by jo-rdan** [comment]
> @jo-rdan Why does Travis pass in your PR without test written?

the PR is passing because there are no tests specified so the process ends with status 0, when the tests are introduced it will fail or pass accordingly

**Comment by Ruqoyah** [comment]
@jo-rdan I get that but the PR initially failed which you also added the screenshot so I'm wondering why it's passing now. And you also stated it here that it's supposed to fail: `this is to update Travis to run tests and initially we do not have tests so it has to fail`

**Comment by jo-rdan** [comment]
> @jo-rdan I get that but the PR initially failed which you also added the screenshot so I'm wondering why it's passing now. And you also stated it here that it's supposed to fail: `this is to update Travis to run tests and initially we do not have tests so it has to fail`

that was because initially on travis.yml file, I specified the script `test` while there was no such script so it failed. Should I re-add it?

**Comment by Ruqoyah** [comment]
@jo-rdan However, I'm going to merge the PR and any issues arise on it later when we start writing tests, we would have to look into it.

**Comment by Ruqoyah** [comment]
@jo-rdan Oh I see! Please add it, when we start writing test then we would expect it to start passing by then. Thanks.

**Comment by jo-rdan** [comment]
> @jo-rdan Oh I see! Please add it, when we start writing test then we would expect it to start passing by then. Thanks.

okay let me add it

**Pull request merged**
